# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aws Albarghouthi's notes
email: albargah@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Aws Albarghouthi's notes
baseurl: "" # the subpath of your site, e.g. /blog
url: "barghouthi.github.io" # the base hostname & protocol for your site
twitter_username: awsTO
github_username:  barghouthi
# Build settings
markdown: kramdown
disqus: barghouthi
